### ISSUE TITLE
Hide message after X seconds

### ISSUE THREAD

**Issue by tatunts** [metadotmy/streamlabs-chat#2]
Hello sir! Thanks for this great work, it is amazing :)

I was wondering if it is possible to make the messages disappear/fade out after some time?

I've noticed that the chat messages stays there forever, taking space in my screen when there's no one sending messages at the time...

Thanks again!

**Comment by metadotmy** [comment]
Hello, 

To hide messages, you can add the code below into the css file. Then you can uncheck the 'Always show messages' and set your preferred time in [streamlabs widget settings](https://imgur.com/a/oppQZeS).

`#log>div {
    animation: fadeOut 0.5s ease {message_hide_delay} forwards;
    -webkit-animation: fadeOut 0.5s ease {message_hide_delay} forwards;
}`

or you can manually set the time directly in the code in which 1 seconds = 1000ms.

`#log>div {
    animation: fadeOut 0.5s ease 5000ms forwards;
    -webkit-animation: fadeOut 0.5s ease 5000ms forwards;
`

**Comment by tatunts** [comment]
Amazing job mate! Worked like a charm, thanks a lot. I'll use it for now on :) Have a great day!

**Comment by tatunts** [comment]
Hello again @metadotmy ! How are you mate?

I've been using your chat custom layout and loving it. thank you very much :)

Sorry to bother you again, but maybe you could help on this topic, since you have a very good background: Is there a way to have any kind of sound for incoming chat messages from StreamLabs? Since I play VR only, its really hard to remember to manually check for new messages. Is there a way to set it up using these custom codes, maybe using javascript, and having a sound playing from my OBS web source (audio monitor)?

I've been searching for a similar solution but could not find it anywhere...

Thank you very much again.

**Comment by metadotmy** [comment]
Hi, I don't really know javascript but maybe you can try this code. I only tested it in browser though. Simply replace the js code like below. You can replace the audio url as needed. If this doesn't work I can't help you further. I'm not a dev or anything and my knowledge is very limited.

```
// Please use event listeners to run functions.
document.addEventListener('onLoad', function(obj) {
    // obj will be empty for chat widget
    // this will fire only once when the widget loads
});

document.addEventListener('onEventReceived', function(obj) {
    // obj will contain information about the event
    if (obj['detail']['command'] === 'PRIVMSG') {
        $('#log>div:last-child').css({
            'opacity': '0',
            'display': 'none'
        }).slideDown(300).animate({
            opacity: 1
        }, 300);
    }

    var audio = new Audio('https://cdn.twitchalerts.com/twitch-bits/sounds/bits.ogg');
    audio.play()
});
```

**Comment by tatunts** [comment]
Oh man.... You have no idea for how I've search for such an elegant solution hahaha Thank you very much, it worked perfectly, just like I want it! Wow, you are a star!!! Have a great day mate!

**Comment by tatunts** [comment]
Hey there! Sorry to bother, again :)

I'm getting some random sounds, no message at all, just the sound plays. Do you think that the trigger event to play the sound could be another one? Or maybe use another evento to listen to the sounds more reliably?

Thanks!

**Comment by tatunts** [comment]
Ohhh boy.... I think I've got what is going on: I have a couple of timers in StreamLabs that sends messages in the chat and since I have those filtered out from my chat web source, they don't show up but the sound does, as they are the same trigger event as a regular chat message... Not sure if there's a workaround for that... Thanks.

**Comment by metadotmy** [comment]
I'm sorry but i don't know how streamlabs handle those events.

**Comment by tatunts** [comment]
No problem! Thanks a lot my friend, you had helped me a lot :) have a great week!

**Comment by metadotmy** [comment]
> Hey there! Sorry to bother, again :)
> 
> I'm getting some random sounds, no message at all, just the sound plays. Do you think that the trigger event to play the sound could be another one? Or maybe use another evento to listen to the sounds more reliably?
> 
> Thanks!

If you hide bot messages by enabling both 'hide chatter' option in streamlabs, you can use code below to now no longer trigger the sound. If you hide bot messages using something else, this solution wouldn't work.

![image](https://user-images.githubusercontent.com/65335648/119600136-fe4ec600-be18-11eb-9111-435603f7064b.png)

````
// Please use event listeners to run functions.
document.addEventListener('onLoad', function(obj) {
    // obj will be empty for chat widget
    // this will fire only once when the widget loads
});


document.addEventListener('onEventReceived', function(obj) {
    // obj will contain information about the event
  	console.log(obj.detail); // OBJ Logs
  
  	// Variables for Bot and Command check. This follows streamlabs' way of doing it.
  	var isCommand = obj.detail.body.charAt(0);
  	var botNames = ["nightbot","moobot","xanbot","deepbot","vivbot","phantombot","streamelements"];
  
    if (obj.detail.command === "PRIVMSG") // Prevent animation for ping events - Curtis Geiger
    {
        if (botNames.indexOf(obj.detail.from) == -1 && isCommand != "!") // Prevent animation if bot
        { 
            $('#log>div').last().hide().slideToggle(600, "easeInOutQuart"); //New animation code
            var audio = new Audio('https://cdn.twitchalerts.com/twitch-bits/sounds/bits.ogg');
            audio.play()
        }    
    }
  
    /* Old animation code - idk which is better tbh.

         if (obj['detail']['command'] === 'PRIVMSG') {
            $('#log>div:last-child').css({
                'opacity': '0',
                'display': 'none'
            }).slideDown(300).animate({
                opacity: 1
            }, 300);
        }

    */
});
```

**Comment by tatunts** [comment]
Thank you very much! I'll give it a try ASAP.
